app = "your-music-bot-123"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false

[[http_service.checks]]
  interval = "30s"
  grace_period = "10s"
  method = "get"
  path = "/"
  timeout = "5s"
