app = "discord-bot-7ci0ha"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true

  [[http_service.checks]]
    interval = "30s"
    grace_period = "10s"
    method = "get"
    path = "/"
    timeout = "5s"
