app = "your-unique-music-bot"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = "10s"
    grace_period = "5s"
    method = "get"
    path = "/"
    timeout = "2s"
